config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, :photos, :albums

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, as: :imageable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord

  mount_uploader :attachment, PhotoUploader

  validates :title, :description, :attachment, presence: true
  validates :title, length: { maximum: 140 }
  validates :description, length: { maximum: 300 }

  belongs_to :imageable, polymorphic: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :email, presence: true

  has_many :photos, as: :imageable
  has_many :albums
  has_many :photos_album, through: :albums, source: :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
  end

  private

  def after_sign_in_path_for(resource_or_scope)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all.page(params[:page]).per(5)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :authenticate_user!

  def index
    @photos = current_user.photos.page(params[:page]).per(4)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render 'new'
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:title, :description, :private, :attachment)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def new
  end

  def create
  end

  def edit
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
  def sharing_mode_options
    [
      ["Private", 1],
      ["Public", 0]
    ]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.slim
= paginate @articles

hr

- @articles.each do |article|
  = article.title
  br

app/views/layouts/application.html.slim
doctype html
html
  head
    title Fotobook
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://use.fontawesome.com/releases/v5.8.1/css/all.css"


    / = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"

  body
    nav class="navbar navbar-default"
      div class="container-fluid"
        div class="navbar-header"
          a class="navbar-brand" == t('fotobook')

        form class="navbar-form navbar-left"
          div class="form-group"
            input[type="text" name="search" class="form-control search-form" placeholder="Seach Photo/Album"]

        ul class="nav navbar-nav navbar-right"
          - if user_signed_in?
            li
              = link_to t("sign_out"), destroy_user_session_path, method: :delete
          - else
            li
              = link_to t("sign_in"), new_user_session_path
            li
              = link_to t("sign_up"), new_user_registration_path

    = yield

app/views/photos/index.html.slim
div.container-fluid.main-container-body#index-photo
  div.row.main-body

    div.col-md-2.vertical-nav
      ul
        li
          a href="#" == t('feeds')
        li
          == link_to t('my_photos'), photos_path
        li
          a href="#" == t('my_albums')


    div.col-md-8.core-content
      div.row
        div.col-md-2.col-md-offset-10
          == link_to "New Photo", new_photo_path, class: "btn btn-success"
      hr

      div.row
        - @photos.each do |photo|
          div [class="col-md-3 photo-col" data-toggle="modal" data-target="#photoModal-#{photo.id}"]
            == image_tag photo.attachment_url, class: "img-thumbnail"

            / .modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="photoModal-#{photo.id}"
            /   .modal-dialog role="document"
            /     .modal-content
            /       .modal-header
            /         button class="close" aria-label="Close" data-dismiss="modal" type="button"
            /             span aria-hidden="true" &times;
            /         h4 id="myModalLabel" class="modal-title" Modal title
            /       .modal-body
            /         == photo.description
            /       .modal-footer

              / div.photo-title
              /   == photo.title

            - if photo.private == 1
                div.rouded-lock
                  i.fas.fa-lock.bottom-left

      = paginate @photos

      / button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#photoModal-bef" Launch demo modal


      - @photos.each do |photo|
        .modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="photoModal-#{photo.id}"
            .modal-dialog role="document"
              .modal-content
                .modal-header
                  button class="close" aria-label="Close" data-dismiss="modal" type="button"
                      span aria-hidden="true" &times;
                  h4 id="myModalLabel" class="modal-title"
                    == photo.title
                .modal-body
                  == image_tag photo.attachment_url, class: "img-thumbnail"

app/views/photos/new.html.slim
div.container-fluid.main-container-body#new-photo
  div.row.main-body

    div.col-md-2.vertical-nav
      ul
        li
          a href="#" == t('feeds')
        li
          == link_to t('my_photos'), photos_path
        li
          a href="#" == t('my_albums')


    div.col-md-8.core-content
        div.row
          div.col-md-12
            h4
              b New Photo
        hr

        div.row
          div.col-md-12
            - if @photo.errors.any?
              h3
                == "#{pluralize(@photo.errors.count, "error")} "
                | prohibited this photo from being saved

              ul
                - @photo.errors.full_messages.each do |msg|
                  li == msg


        = form_with model: @photo, local: true, id: "new-photo-form" do |f|
          div.row
              div.col-md-6
                div.form-group
                  = f.label :title
                  = f.text_field :title, class: "form-control", placeholder: "Photo title", autofocus: true

                div.row
                  div.col-md-6
                    div.form-group
                      = f.label :sharing_mode
                      = f.select :private, options_for_select(sharing_mode_options), {}, class: "form-control"


              div.col-md-6
                div.form-group
                  = f.label :description
                  = f.text_area :description, class: "form-control", placeholder: "Photo Description"

          div.row
            div.col-md-3.upload-button
              div#square
                i.fas.fa-plus
              img id="photo-preview"

            div.col-md-3.upload-field
              div.form-group
              = f.file_field :attachment


          div.row
            div.col-md-6
              = f.submit "Save", class: "btn btn-success"
javascript:
  NewPhoto.run()

app/views/users/edit.html.slim
= form_with model: @user do |f|
  div class = "form-group"
    = f.label :firstname
    = f.text_field :first_name, class: "form-control"

  div class = "form-group"
    = f.label :lastname
    = f.text_field :last_name, class: "form-control"

  div class = "form-group"
    = f.label :email
    = f.email_field :email, class: "form-control"

  - if @user.avatar?
      = image_tag @user.avatar.thumb.url
      = link_to "Remove Avatar", destroy_avatar_user_path(id: current_user.id), method: :delete
  - else
      div class="field"
        = f.file_field :avatar

  = f.submit

app/views/users/new.html.slim
= render 'form', user: @user

app/views/users/show.html.slim
div class="container-fluid"
  div class="row main-body"

    div class="col-md-2 vertical-nav"
      ul
        li
          a href="#" == t('feeds')
        li
          == link_to t('my_photos'), photos_path
        li
          a href="#" == t('my_albums')


    div class="col-md-8"

    div class="col-md-2"